title: Andor Polgar's photolog
email: hngrhorace@gmail.com
description: >
  I'm a man of few words, so here's my photolog.
baseurl: ""
url: "http://andor.cool"
twitter_username: hngrhorace
github_username:  andormade
imagehost_url: "http://images.andor.cool"
paginate: 6
paginate_path: "/pages/:num/"

sass:
    sass_dir: _sass
    style: compressed

# Build settings
markdown: kramdown
