title: Andor Polgar's photolog
email: hngrhorace@gmail.com
description: >
  My name is Andor, I'm a hungarian software developer living in Haarlem, North Holland.
  I enjoy making music with my modular synthesizers and documenting my life through photography.
baseurl: ""
url: "http://andor.cool"
twitter_username: hngrhorace
github_username:  andormade
imagehost_url: "http://images.andor.cool"
paginate: 8
paginate_path: "/pages/:num/"
exclude: ["README.md", "Gemfile.lock", "Gemfile"]
include: [".htaccess"]
permalink: /:categories/:year/:month/:day/:title

sass:
    sass_dir: _sass
    style: compressed

# Build settings
markdown: kramdown
